spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/drom_db
    password: root
    username: root
  security:
    user:
      password: 1
      name: 1